### ISSUE TITLE
could you elabrate what is the case? I am very interested and python

### ISSUE THREAD

**Issue by daviddhc20120601** [grngr/capgemini_demo#1]
could you elabrate what is the case? I am very interested and python, Haidong,chen@cap

**Comment by daviddhc20120601** [comment]
I was thinking we could hook blockchain at backend and make it awesome agagin

**Comment by grngr** [comment]
Hello Haidong, good day! Let's connect over Skype tomorrow. Shall ping you.

**Comment by daviddhc20120601** [comment]
would be great, could u ping me on skype? I am Haidong Chen on skype

Sent from my iPhone

On Apr 25, 2019, at 23:50, grngr <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Haidong, good day! Let's connect over Skype tomorrow. Shall ping you.

**Comment by grngr** [comment]
we connected
